# Generated by Django 3.1.3 on 2021-04-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_delete_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('preferred_date', models.DateField(verbose_name='preferred date')),
                ('picked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Wait List',
                'ordering': ['create_at', 'picked'],
            },
        ),
    ]
